// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: redns_rpc.proto

package redns_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Result int32

const (
	Result_success   Result = 0
	Result_not_found Result = 1
)

// Enum value maps for Result.
var (
	Result_name = map[int32]string{
		0: "success",
		1: "not_found",
	}
	Result_value = map[string]int32{
		"success":   0,
		"not_found": 1,
	}
)

func (x Result) Enum() *Result {
	p := new(Result)
	*p = x
	return p
}

func (x Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Result) Descriptor() protoreflect.EnumDescriptor {
	return file_redns_rpc_proto_enumTypes[0].Descriptor()
}

func (Result) Type() protoreflect.EnumType {
	return &file_redns_rpc_proto_enumTypes[0]
}

func (x Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Result.Descriptor instead.
func (Result) EnumDescriptor() ([]byte, []int) {
	return file_redns_rpc_proto_rawDescGZIP(), []int{0}
}

type DetailedStrayEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QName    string `protobuf:"bytes,1,opt,name=QName,proto3" json:"QName,omitempty"`
	QType    string `protobuf:"bytes,2,opt,name=QType,proto3" json:"QType,omitempty"`
	Id       string `protobuf:"bytes,3,opt,name=Id,proto3" json:"Id,omitempty"`
	Rfc1035  string `protobuf:"bytes,4,opt,name=Rfc1035,proto3" json:"Rfc1035,omitempty"`
	Expiry   uint32 `protobuf:"varint,5,opt,name=Expiry,proto3" json:"Expiry,omitempty"`
	RedisKey string `protobuf:"bytes,6,opt,name=RedisKey,proto3" json:"RedisKey,omitempty"`
}

func (x *DetailedStrayEntity) Reset() {
	*x = DetailedStrayEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redns_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetailedStrayEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailedStrayEntity) ProtoMessage() {}

func (x *DetailedStrayEntity) ProtoReflect() protoreflect.Message {
	mi := &file_redns_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailedStrayEntity.ProtoReflect.Descriptor instead.
func (*DetailedStrayEntity) Descriptor() ([]byte, []int) {
	return file_redns_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *DetailedStrayEntity) GetQName() string {
	if x != nil {
		return x.QName
	}
	return ""
}

func (x *DetailedStrayEntity) GetQType() string {
	if x != nil {
		return x.QType
	}
	return ""
}

func (x *DetailedStrayEntity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DetailedStrayEntity) GetRfc1035() string {
	if x != nil {
		return x.Rfc1035
	}
	return ""
}

func (x *DetailedStrayEntity) GetExpiry() uint32 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

func (x *DetailedStrayEntity) GetRedisKey() string {
	if x != nil {
		return x.RedisKey
	}
	return ""
}

type RRidentifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QName string `protobuf:"bytes,1,opt,name=QName,proto3" json:"QName,omitempty"`
	QType string `protobuf:"bytes,2,opt,name=QType,proto3" json:"QType,omitempty"`
}

func (x *RRidentifier) Reset() {
	*x = RRidentifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redns_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RRidentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RRidentifier) ProtoMessage() {}

func (x *RRidentifier) ProtoReflect() protoreflect.Message {
	mi := &file_redns_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RRidentifier.ProtoReflect.Descriptor instead.
func (*RRidentifier) Descriptor() ([]byte, []int) {
	return file_redns_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *RRidentifier) GetQName() string {
	if x != nil {
		return x.QName
	}
	return ""
}

func (x *RRidentifier) GetQType() string {
	if x != nil {
		return x.QType
	}
	return ""
}

type StrayEntity2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Selector:
	//
	//	*StrayEntity2_Identifier
	//	*StrayEntity2_Rfc1035
	Selector isStrayEntity2_Selector `protobuf_oneof:"selector"`
	Id       string                  `protobuf:"bytes,3,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *StrayEntity2) Reset() {
	*x = StrayEntity2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redns_rpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StrayEntity2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrayEntity2) ProtoMessage() {}

func (x *StrayEntity2) ProtoReflect() protoreflect.Message {
	mi := &file_redns_rpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrayEntity2.ProtoReflect.Descriptor instead.
func (*StrayEntity2) Descriptor() ([]byte, []int) {
	return file_redns_rpc_proto_rawDescGZIP(), []int{2}
}

func (m *StrayEntity2) GetSelector() isStrayEntity2_Selector {
	if m != nil {
		return m.Selector
	}
	return nil
}

func (x *StrayEntity2) GetIdentifier() *RRidentifier {
	if x, ok := x.GetSelector().(*StrayEntity2_Identifier); ok {
		return x.Identifier
	}
	return nil
}

func (x *StrayEntity2) GetRfc1035() string {
	if x, ok := x.GetSelector().(*StrayEntity2_Rfc1035); ok {
		return x.Rfc1035
	}
	return ""
}

func (x *StrayEntity2) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type isStrayEntity2_Selector interface {
	isStrayEntity2_Selector()
}

type StrayEntity2_Identifier struct {
	Identifier *RRidentifier `protobuf:"bytes,1,opt,name=identifier,proto3,oneof"`
}

type StrayEntity2_Rfc1035 struct {
	Rfc1035 string `protobuf:"bytes,2,opt,name=Rfc1035,proto3,oneof"`
}

func (*StrayEntity2_Identifier) isStrayEntity2_Selector() {}

func (*StrayEntity2_Rfc1035) isStrayEntity2_Selector() {}

type StrayEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QName string `protobuf:"bytes,1,opt,name=QName,proto3" json:"QName,omitempty"`
	QType string `protobuf:"bytes,2,opt,name=QType,proto3" json:"QType,omitempty"`
	Id    string `protobuf:"bytes,3,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *StrayEntity) Reset() {
	*x = StrayEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redns_rpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StrayEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrayEntity) ProtoMessage() {}

func (x *StrayEntity) ProtoReflect() protoreflect.Message {
	mi := &file_redns_rpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrayEntity.ProtoReflect.Descriptor instead.
func (*StrayEntity) Descriptor() ([]byte, []int) {
	return file_redns_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *StrayEntity) GetQName() string {
	if x != nil {
		return x.QName
	}
	return ""
}

func (x *StrayEntity) GetQType() string {
	if x != nil {
		return x.QType
	}
	return ""
}

func (x *StrayEntity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StrayDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QName string `protobuf:"bytes,1,opt,name=QName,proto3" json:"QName,omitempty"`
	QType string `protobuf:"bytes,2,opt,name=QType,proto3" json:"QType,omitempty"`
	Id    string `protobuf:"bytes,3,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *StrayDeleteRequest) Reset() {
	*x = StrayDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redns_rpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StrayDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrayDeleteRequest) ProtoMessage() {}

func (x *StrayDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redns_rpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrayDeleteRequest.ProtoReflect.Descriptor instead.
func (*StrayDeleteRequest) Descriptor() ([]byte, []int) {
	return file_redns_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *StrayDeleteRequest) GetQName() string {
	if x != nil {
		return x.QName
	}
	return ""
}

func (x *StrayDeleteRequest) GetQType() string {
	if x != nil {
		return x.QType
	}
	return ""
}

func (x *StrayDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StrayDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Server       string `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	RowsAffected uint32 `protobuf:"varint,2,opt,name=rowsAffected,proto3" json:"rowsAffected,omitempty"`
}

func (x *StrayDeleteResponse) Reset() {
	*x = StrayDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redns_rpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StrayDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrayDeleteResponse) ProtoMessage() {}

func (x *StrayDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redns_rpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrayDeleteResponse.ProtoReflect.Descriptor instead.
func (*StrayDeleteResponse) Descriptor() ([]byte, []int) {
	return file_redns_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *StrayDeleteResponse) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *StrayDeleteResponse) GetRowsAffected() uint32 {
	if x != nil {
		return x.RowsAffected
	}
	return 0
}

type PerServerStrayDeleteByIdResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *StrayEntity           `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Results []*StrayDeleteResponse `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *PerServerStrayDeleteByIdResult) Reset() {
	*x = PerServerStrayDeleteByIdResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redns_rpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PerServerStrayDeleteByIdResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerServerStrayDeleteByIdResult) ProtoMessage() {}

func (x *PerServerStrayDeleteByIdResult) ProtoReflect() protoreflect.Message {
	mi := &file_redns_rpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerServerStrayDeleteByIdResult.ProtoReflect.Descriptor instead.
func (*PerServerStrayDeleteByIdResult) Descriptor() ([]byte, []int) {
	return file_redns_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *PerServerStrayDeleteByIdResult) GetRequest() *StrayEntity {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *PerServerStrayDeleteByIdResult) GetResults() []*StrayDeleteResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

type StrayByValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rfc1035 string `protobuf:"bytes,2,opt,name=Rfc1035,proto3" json:"Rfc1035,omitempty"`
}

func (x *StrayByValueRequest) Reset() {
	*x = StrayByValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redns_rpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StrayByValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrayByValueRequest) ProtoMessage() {}

func (x *StrayByValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redns_rpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrayByValueRequest.ProtoReflect.Descriptor instead.
func (*StrayByValueRequest) Descriptor() ([]byte, []int) {
	return file_redns_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *StrayByValueRequest) GetRfc1035() string {
	if x != nil {
		return x.Rfc1035
	}
	return ""
}

type StrayDeleteResponses struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*StrayDeleteResponse `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *StrayDeleteResponses) Reset() {
	*x = StrayDeleteResponses{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redns_rpc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StrayDeleteResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrayDeleteResponses) ProtoMessage() {}

func (x *StrayDeleteResponses) ProtoReflect() protoreflect.Message {
	mi := &file_redns_rpc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrayDeleteResponses.ProtoReflect.Descriptor instead.
func (*StrayDeleteResponses) Descriptor() ([]byte, []int) {
	return file_redns_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *StrayDeleteResponses) GetResults() []*StrayDeleteResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

type StrayModifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string  `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Rfc1035        string  `protobuf:"bytes,2,opt,name=Rfc1035,proto3" json:"Rfc1035,omitempty"`
	Expiry         *uint32 `protobuf:"varint,3,opt,name=Expiry,proto3,oneof" json:"Expiry,omitempty"`
	AllowOverwrite bool    `protobuf:"varint,4,opt,name=AllowOverwrite,proto3" json:"AllowOverwrite,omitempty"`
}

func (x *StrayModifyRequest) Reset() {
	*x = StrayModifyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redns_rpc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StrayModifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrayModifyRequest) ProtoMessage() {}

func (x *StrayModifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redns_rpc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrayModifyRequest.ProtoReflect.Descriptor instead.
func (*StrayModifyRequest) Descriptor() ([]byte, []int) {
	return file_redns_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *StrayModifyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StrayModifyRequest) GetRfc1035() string {
	if x != nil {
		return x.Rfc1035
	}
	return ""
}

func (x *StrayModifyRequest) GetExpiry() uint32 {
	if x != nil && x.Expiry != nil {
		return *x.Expiry
	}
	return 0
}

func (x *StrayModifyRequest) GetAllowOverwrite() bool {
	if x != nil {
		return x.AllowOverwrite
	}
	return false
}

type StrayModifyRequests struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reqs []*StrayModifyRequest `protobuf:"bytes,1,rep,name=reqs,proto3" json:"reqs,omitempty"`
}

func (x *StrayModifyRequests) Reset() {
	*x = StrayModifyRequests{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redns_rpc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StrayModifyRequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrayModifyRequests) ProtoMessage() {}

func (x *StrayModifyRequests) ProtoReflect() protoreflect.Message {
	mi := &file_redns_rpc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrayModifyRequests.ProtoReflect.Descriptor instead.
func (*StrayModifyRequests) Descriptor() ([]byte, []int) {
	return file_redns_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *StrayModifyRequests) GetReqs() []*StrayModifyRequest {
	if x != nil {
		return x.Reqs
	}
	return nil
}

type StrayModifyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *StrayModifyRequest `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Result  string              `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *StrayModifyResponse) Reset() {
	*x = StrayModifyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redns_rpc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StrayModifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrayModifyResponse) ProtoMessage() {}

func (x *StrayModifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redns_rpc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrayModifyResponse.ProtoReflect.Descriptor instead.
func (*StrayModifyResponse) Descriptor() ([]byte, []int) {
	return file_redns_rpc_proto_rawDescGZIP(), []int{11}
}

func (x *StrayModifyResponse) GetRequest() *StrayModifyRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *StrayModifyResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type StrayModifyResponses struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reqs []*StrayModifyResponse `protobuf:"bytes,1,rep,name=reqs,proto3" json:"reqs,omitempty"`
}

func (x *StrayModifyResponses) Reset() {
	*x = StrayModifyResponses{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redns_rpc_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StrayModifyResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrayModifyResponses) ProtoMessage() {}

func (x *StrayModifyResponses) ProtoReflect() protoreflect.Message {
	mi := &file_redns_rpc_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrayModifyResponses.ProtoReflect.Descriptor instead.
func (*StrayModifyResponses) Descriptor() ([]byte, []int) {
	return file_redns_rpc_proto_rawDescGZIP(), []int{12}
}

func (x *StrayModifyResponses) GetReqs() []*StrayModifyResponse {
	if x != nil {
		return x.Reqs
	}
	return nil
}

type ResultMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *string `protobuf:"bytes,1,opt,name=message,proto3,oneof" json:"message,omitempty"`
}

func (x *ResultMsg) Reset() {
	*x = ResultMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redns_rpc_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultMsg) ProtoMessage() {}

func (x *ResultMsg) ProtoReflect() protoreflect.Message {
	mi := &file_redns_rpc_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultMsg.ProtoReflect.Descriptor instead.
func (*ResultMsg) Descriptor() ([]byte, []int) {
	return file_redns_rpc_proto_rawDescGZIP(), []int{13}
}

func (x *ResultMsg) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type AddGenerationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AddGenerationRequest) Reset() {
	*x = AddGenerationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redns_rpc_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGenerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGenerationRequest) ProtoMessage() {}

func (x *AddGenerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redns_rpc_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGenerationRequest.ProtoReflect.Descriptor instead.
func (*AddGenerationRequest) Descriptor() ([]byte, []int) {
	return file_redns_rpc_proto_rawDescGZIP(), []int{14}
}

func (x *AddGenerationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddGenerationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AffectedRecordsCount uint32 `protobuf:"varint,1,opt,name=affectedRecordsCount,proto3" json:"affectedRecordsCount,omitempty"`
}

func (x *AddGenerationResponse) Reset() {
	*x = AddGenerationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redns_rpc_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGenerationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGenerationResponse) ProtoMessage() {}

func (x *AddGenerationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redns_rpc_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGenerationResponse.ProtoReflect.Descriptor instead.
func (*AddGenerationResponse) Descriptor() ([]byte, []int) {
	return file_redns_rpc_proto_rawDescGZIP(), []int{15}
}

func (x *AddGenerationResponse) GetAffectedRecordsCount() uint32 {
	if x != nil {
		return x.AffectedRecordsCount
	}
	return 0
}

type Rfc1035 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rfc1035 string `protobuf:"bytes,1,opt,name=Rfc1035,proto3" json:"Rfc1035,omitempty"`
}

func (x *Rfc1035) Reset() {
	*x = Rfc1035{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redns_rpc_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rfc1035) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rfc1035) ProtoMessage() {}

func (x *Rfc1035) ProtoReflect() protoreflect.Message {
	mi := &file_redns_rpc_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rfc1035.ProtoReflect.Descriptor instead.
func (*Rfc1035) Descriptor() ([]byte, []int) {
	return file_redns_rpc_proto_rawDescGZIP(), []int{16}
}

func (x *Rfc1035) GetRfc1035() string {
	if x != nil {
		return x.Rfc1035
	}
	return ""
}

type DeleteGenerationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteGenerationRequest) Reset() {
	*x = DeleteGenerationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redns_rpc_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGenerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGenerationRequest) ProtoMessage() {}

func (x *DeleteGenerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redns_rpc_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGenerationRequest.ProtoReflect.Descriptor instead.
func (*DeleteGenerationRequest) Descriptor() ([]byte, []int) {
	return file_redns_rpc_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteGenerationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RednsGenerationDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Server               string `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	AffectedRecordsCount uint32 `protobuf:"varint,2,opt,name=affectedRecordsCount,proto3" json:"affectedRecordsCount,omitempty"`
}

func (x *RednsGenerationDeleteResponse) Reset() {
	*x = RednsGenerationDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redns_rpc_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RednsGenerationDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RednsGenerationDeleteResponse) ProtoMessage() {}

func (x *RednsGenerationDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redns_rpc_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RednsGenerationDeleteResponse.ProtoReflect.Descriptor instead.
func (*RednsGenerationDeleteResponse) Descriptor() ([]byte, []int) {
	return file_redns_rpc_proto_rawDescGZIP(), []int{18}
}

func (x *RednsGenerationDeleteResponse) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *RednsGenerationDeleteResponse) GetAffectedRecordsCount() uint32 {
	if x != nil {
		return x.AffectedRecordsCount
	}
	return 0
}

type PerServerRednsGenerationDeleteByIdResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*RednsGenerationDeleteResponse `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *PerServerRednsGenerationDeleteByIdResult) Reset() {
	*x = PerServerRednsGenerationDeleteByIdResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redns_rpc_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PerServerRednsGenerationDeleteByIdResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerServerRednsGenerationDeleteByIdResult) ProtoMessage() {}

func (x *PerServerRednsGenerationDeleteByIdResult) ProtoReflect() protoreflect.Message {
	mi := &file_redns_rpc_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerServerRednsGenerationDeleteByIdResult.ProtoReflect.Descriptor instead.
func (*PerServerRednsGenerationDeleteByIdResult) Descriptor() ([]byte, []int) {
	return file_redns_rpc_proto_rawDescGZIP(), []int{19}
}

func (x *PerServerRednsGenerationDeleteByIdResult) GetResults() []*RednsGenerationDeleteResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_redns_rpc_proto protoreflect.FileDescriptor

var file_redns_rpc_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x72, 0x65, 0x64, 0x6e, 0x73, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x15, 0x79, 0x37, 0x5f, 0x72, 0x65, 0x64, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x76, 0x31, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9f, 0x01, 0x0a, 0x13, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x65, 0x64, 0x53, 0x74, 0x72, 0x61, 0x79, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x51, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x51, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x51, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x51, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x66, 0x63,
	0x31, 0x30, 0x33, 0x35, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x52, 0x66, 0x63, 0x31,
	0x30, 0x33, 0x35, 0x12, 0x16, 0x0a, 0x06, 0x45, 0x78, 0x70, 0x69, 0x72, 0x79, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x45, 0x78, 0x70, 0x69, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x52,
	0x65, 0x64, 0x69, 0x73, 0x4b, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52,
	0x65, 0x64, 0x69, 0x73, 0x4b, 0x65, 0x79, 0x22, 0x3a, 0x0a, 0x0c, 0x52, 0x52, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x51, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x51, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x51, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x51, 0x54,
	0x79, 0x70, 0x65, 0x22, 0x8d, 0x01, 0x0a, 0x0c, 0x53, 0x74, 0x72, 0x61, 0x79, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x32, 0x12, 0x45, 0x0a, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x79, 0x37, 0x5f, 0x72, 0x65,
	0x64, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x76, 0x31,
	0x2e, 0x52, 0x52, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x48, 0x00, 0x52,
	0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x07, 0x52,
	0x66, 0x63, 0x31, 0x30, 0x33, 0x35, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07,
	0x52, 0x66, 0x63, 0x31, 0x30, 0x33, 0x35, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x42, 0x0a, 0x0a, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x22, 0x49, 0x0a, 0x0b, 0x53, 0x74, 0x72, 0x61, 0x79, 0x45, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x51, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x51, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x51, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x51, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x22, 0x50,
	0x0a, 0x12, 0x53, 0x74, 0x72, 0x61, 0x79, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x51, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x51, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x51, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x51, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64,
	0x22, 0x51, 0x0a, 0x13, 0x53, 0x74, 0x72, 0x61, 0x79, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12,
	0x22, 0x0a, 0x0c, 0x72, 0x6f, 0x77, 0x73, 0x41, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x72, 0x6f, 0x77, 0x73, 0x41, 0x66, 0x66, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x22, 0xa4, 0x01, 0x0a, 0x1e, 0x50, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x53, 0x74, 0x72, 0x61, 0x79, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x79, 0x49, 0x64,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x3c, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x79, 0x37, 0x5f, 0x72, 0x65, 0x64,
	0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x76, 0x31, 0x2e,
	0x53, 0x74, 0x72, 0x61, 0x79, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x07, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x44, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x79, 0x37, 0x5f, 0x72, 0x65, 0x64, 0x6e, 0x73,
	0x5f, 0x61, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x76, 0x31, 0x2e, 0x53, 0x74,
	0x72, 0x61, 0x79, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x2f, 0x0a, 0x13, 0x53, 0x74,
	0x72, 0x61, 0x79, 0x42, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x66, 0x63, 0x31, 0x30, 0x33, 0x35, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x52, 0x66, 0x63, 0x31, 0x30, 0x33, 0x35, 0x22, 0x5c, 0x0a, 0x14, 0x53,
	0x74, 0x72, 0x61, 0x79, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x73, 0x12, 0x44, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x79, 0x37, 0x5f, 0x72, 0x65, 0x64, 0x6e, 0x73, 0x5f,
	0x61, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x72,
	0x61, 0x79, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x8e, 0x01, 0x0a, 0x12, 0x53, 0x74,
	0x72, 0x61, 0x79, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x52, 0x66, 0x63, 0x31, 0x30, 0x33, 0x35, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x52, 0x66, 0x63, 0x31, 0x30, 0x33, 0x35, 0x12, 0x1b, 0x0a, 0x06, 0x45, 0x78,
	0x70, 0x69, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x06, 0x45, 0x78,
	0x70, 0x69, 0x72, 0x79, 0x88, 0x01, 0x01, 0x12, 0x26, 0x0a, 0x0e, 0x41, 0x6c, 0x6c, 0x6f, 0x77,
	0x4f, 0x76, 0x65, 0x72, 0x77, 0x72, 0x69, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0e, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x4f, 0x76, 0x65, 0x72, 0x77, 0x72, 0x69, 0x74, 0x65, 0x42,
	0x09, 0x0a, 0x07, 0x5f, 0x45, 0x78, 0x70, 0x69, 0x72, 0x79, 0x22, 0x54, 0x0a, 0x13, 0x53, 0x74,
	0x72, 0x61, 0x79, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x73, 0x12, 0x3d, 0x0a, 0x04, 0x72, 0x65, 0x71, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x29, 0x2e, 0x79, 0x37, 0x5f, 0x72, 0x65, 0x64, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x5f, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x72, 0x61, 0x79, 0x4d, 0x6f, 0x64,
	0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x04, 0x72, 0x65, 0x71, 0x73,
	0x22, 0x72, 0x0a, 0x13, 0x53, 0x74, 0x72, 0x61, 0x79, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x79, 0x37, 0x5f, 0x72, 0x65,
	0x64, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x76, 0x31,
	0x2e, 0x53, 0x74, 0x72, 0x61, 0x79, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x56, 0x0a, 0x14, 0x53, 0x74, 0x72, 0x61, 0x79, 0x4d, 0x6f, 0x64,
	0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x12, 0x3e, 0x0a, 0x04,
	0x72, 0x65, 0x71, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x79, 0x37, 0x5f,
	0x72, 0x65, 0x64, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f,
	0x76, 0x31, 0x2e, 0x53, 0x74, 0x72, 0x61, 0x79, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x72, 0x65, 0x71, 0x73, 0x22, 0x36, 0x0a, 0x09,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x1d, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x26, 0x0a, 0x14, 0x41, 0x64, 0x64, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4b, 0x0a, 0x15,
	0x41, 0x64, 0x64, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x14, 0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65,
	0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x14, 0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x23, 0x0a, 0x07, 0x52, 0x66, 0x63,
	0x31, 0x30, 0x33, 0x35, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x66, 0x63, 0x31, 0x30, 0x33, 0x35, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x52, 0x66, 0x63, 0x31, 0x30, 0x33, 0x35, 0x22, 0x29,
	0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x6b, 0x0a, 0x1d, 0x52, 0x65, 0x64,
	0x6e, 0x73, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x12, 0x32, 0x0a, 0x14, 0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x14, 0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x7a, 0x0a, 0x28, 0x50, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x64, 0x6e, 0x73, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x4e, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x79, 0x37, 0x5f, 0x72, 0x65, 0x64, 0x6e, 0x73, 0x5f, 0x61,
	0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x64, 0x6e,
	0x73, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x2a, 0x24, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0b, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x6e, 0x6f, 0x74,
	0x5f, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0x01, 0x32, 0x98, 0x04, 0x0a, 0x05, 0x53, 0x74, 0x72,
	0x61, 0x79, 0x12, 0x4e, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x53, 0x74, 0x72, 0x61, 0x79, 0x12, 0x2a,
	0x2e, 0x79, 0x37, 0x5f, 0x72, 0x65, 0x64, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x5f, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x72, 0x61, 0x79, 0x4d, 0x6f, 0x64, 0x69,
	0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x12, 0x51, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x53, 0x74, 0x72, 0x61, 0x79, 0x73, 0x12,
	0x2a, 0x2e, 0x79, 0x37, 0x5f, 0x72, 0x65, 0x64, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x5f, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x72, 0x61, 0x79, 0x4d, 0x6f, 0x64,
	0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x28, 0x01, 0x12, 0x52, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x72,
	0x61, 0x79, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x2a, 0x2e, 0x79, 0x37,
	0x5f, 0x72, 0x65, 0x64, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x5f, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x53, 0x74, 0x72, 0x61,
	0x79, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x30, 0x01, 0x12, 0x4d, 0x0a, 0x0f, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x53, 0x74, 0x72, 0x61, 0x79, 0x42, 0x79, 0x49, 0x64, 0x12, 0x22, 0x2e, 0x79,
	0x37, 0x5f, 0x72, 0x65, 0x64, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x5f, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x72, 0x61, 0x79, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x6d, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x53, 0x74, 0x72, 0x61, 0x79, 0x42, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x2a,
	0x2e, 0x79, 0x37, 0x5f, 0x72, 0x65, 0x64, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x5f, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x72, 0x61, 0x79, 0x42, 0x79, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x79, 0x37, 0x5f,
	0x72, 0x65, 0x64, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f,
	0x76, 0x31, 0x2e, 0x53, 0x74, 0x72, 0x61, 0x79, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x12, 0x5a, 0x0a, 0x0b, 0x4d, 0x6f, 0x64, 0x69, 0x66,
	0x79, 0x53, 0x74, 0x72, 0x61, 0x79, 0x12, 0x29, 0x2e, 0x79, 0x37, 0x5f, 0x72, 0x65, 0x64, 0x6e,
	0x73, 0x5f, 0x61, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x76, 0x31, 0x2e, 0x53,
	0x74, 0x72, 0x61, 0x79, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x20, 0x2e, 0x79, 0x37, 0x5f, 0x72, 0x65, 0x64, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x4d, 0x73, 0x67, 0x32, 0xf2, 0x01, 0x0a, 0x05, 0x52, 0x65, 0x64, 0x6e, 0x73, 0x12, 0x5f, 0x0a,
	0x0d, 0x41, 0x64, 0x64, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e,
	0x2e, 0x79, 0x37, 0x5f, 0x72, 0x65, 0x64, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x5f, 0x76, 0x31, 0x2e, 0x52, 0x66, 0x63, 0x31, 0x30, 0x33, 0x35, 0x1a, 0x2c,
	0x2e, 0x79, 0x37, 0x5f, 0x72, 0x65, 0x64, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x5f, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x12, 0x87,
	0x01, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x42, 0x79, 0x49, 0x64, 0x12, 0x2e, 0x2e, 0x79, 0x37, 0x5f, 0x72, 0x65, 0x64,
	0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x76, 0x31, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3f, 0x2e, 0x79, 0x37, 0x5f, 0x72, 0x65, 0x64,
	0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x76, 0x31, 0x2e,
	0x50, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x64, 0x6e, 0x73, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6e, 0x64, 0x72, 0x65, 0x73, 0x7a, 0x61, 0x62,
	0x6f, 0x2f, 0x72, 0x65, 0x64, 0x6e, 0x73, 0x2d, 0x61, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x72, 0x65, 0x64, 0x6e, 0x73, 0x5f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_redns_rpc_proto_rawDescOnce sync.Once
	file_redns_rpc_proto_rawDescData = file_redns_rpc_proto_rawDesc
)

func file_redns_rpc_proto_rawDescGZIP() []byte {
	file_redns_rpc_proto_rawDescOnce.Do(func() {
		file_redns_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_redns_rpc_proto_rawDescData)
	})
	return file_redns_rpc_proto_rawDescData
}

var file_redns_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_redns_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_redns_rpc_proto_goTypes = []interface{}{
	(Result)(0),                                      // 0: y7_redns_apiserver_v1.Result
	(*DetailedStrayEntity)(nil),                      // 1: y7_redns_apiserver_v1.DetailedStrayEntity
	(*RRidentifier)(nil),                             // 2: y7_redns_apiserver_v1.RRidentifier
	(*StrayEntity2)(nil),                             // 3: y7_redns_apiserver_v1.StrayEntity2
	(*StrayEntity)(nil),                              // 4: y7_redns_apiserver_v1.StrayEntity
	(*StrayDeleteRequest)(nil),                       // 5: y7_redns_apiserver_v1.StrayDeleteRequest
	(*StrayDeleteResponse)(nil),                      // 6: y7_redns_apiserver_v1.StrayDeleteResponse
	(*PerServerStrayDeleteByIdResult)(nil),           // 7: y7_redns_apiserver_v1.PerServerStrayDeleteByIdResult
	(*StrayByValueRequest)(nil),                      // 8: y7_redns_apiserver_v1.StrayByValueRequest
	(*StrayDeleteResponses)(nil),                     // 9: y7_redns_apiserver_v1.StrayDeleteResponses
	(*StrayModifyRequest)(nil),                       // 10: y7_redns_apiserver_v1.StrayModifyRequest
	(*StrayModifyRequests)(nil),                      // 11: y7_redns_apiserver_v1.StrayModifyRequests
	(*StrayModifyResponse)(nil),                      // 12: y7_redns_apiserver_v1.StrayModifyResponse
	(*StrayModifyResponses)(nil),                     // 13: y7_redns_apiserver_v1.StrayModifyResponses
	(*ResultMsg)(nil),                                // 14: y7_redns_apiserver_v1.ResultMsg
	(*AddGenerationRequest)(nil),                     // 15: y7_redns_apiserver_v1.AddGenerationRequest
	(*AddGenerationResponse)(nil),                    // 16: y7_redns_apiserver_v1.AddGenerationResponse
	(*Rfc1035)(nil),                                  // 17: y7_redns_apiserver_v1.Rfc1035
	(*DeleteGenerationRequest)(nil),                  // 18: y7_redns_apiserver_v1.DeleteGenerationRequest
	(*RednsGenerationDeleteResponse)(nil),            // 19: y7_redns_apiserver_v1.RednsGenerationDeleteResponse
	(*PerServerRednsGenerationDeleteByIdResult)(nil), // 20: y7_redns_apiserver_v1.PerServerRednsGenerationDeleteByIdResult
	(*emptypb.Empty)(nil),                            // 21: google.protobuf.Empty
}
var file_redns_rpc_proto_depIdxs = []int32{
	2,  // 0: y7_redns_apiserver_v1.StrayEntity2.identifier:type_name -> y7_redns_apiserver_v1.RRidentifier
	4,  // 1: y7_redns_apiserver_v1.PerServerStrayDeleteByIdResult.request:type_name -> y7_redns_apiserver_v1.StrayEntity
	6,  // 2: y7_redns_apiserver_v1.PerServerStrayDeleteByIdResult.results:type_name -> y7_redns_apiserver_v1.StrayDeleteResponse
	6,  // 3: y7_redns_apiserver_v1.StrayDeleteResponses.results:type_name -> y7_redns_apiserver_v1.StrayDeleteResponse
	10, // 4: y7_redns_apiserver_v1.StrayModifyRequests.reqs:type_name -> y7_redns_apiserver_v1.StrayModifyRequest
	10, // 5: y7_redns_apiserver_v1.StrayModifyResponse.request:type_name -> y7_redns_apiserver_v1.StrayModifyRequest
	12, // 6: y7_redns_apiserver_v1.StrayModifyResponses.reqs:type_name -> y7_redns_apiserver_v1.StrayModifyResponse
	19, // 7: y7_redns_apiserver_v1.PerServerRednsGenerationDeleteByIdResult.results:type_name -> y7_redns_apiserver_v1.RednsGenerationDeleteResponse
	11, // 8: y7_redns_apiserver_v1.Stray.AddStray:input_type -> y7_redns_apiserver_v1.StrayModifyRequests
	11, // 9: y7_redns_apiserver_v1.Stray.AddStrays:input_type -> y7_redns_apiserver_v1.StrayModifyRequests
	21, // 10: y7_redns_apiserver_v1.Stray.ListStrays:input_type -> google.protobuf.Empty
	4,  // 11: y7_redns_apiserver_v1.Stray.DeleteStrayById:input_type -> y7_redns_apiserver_v1.StrayEntity
	8,  // 12: y7_redns_apiserver_v1.Stray.DeleteStrayByValue:input_type -> y7_redns_apiserver_v1.StrayByValueRequest
	10, // 13: y7_redns_apiserver_v1.Stray.ModifyStray:input_type -> y7_redns_apiserver_v1.StrayModifyRequest
	17, // 14: y7_redns_apiserver_v1.Redns.AddGeneration:input_type -> y7_redns_apiserver_v1.Rfc1035
	18, // 15: y7_redns_apiserver_v1.Redns.DeleteGenerationById:input_type -> y7_redns_apiserver_v1.DeleteGenerationRequest
	21, // 16: y7_redns_apiserver_v1.Stray.AddStray:output_type -> google.protobuf.Empty
	21, // 17: y7_redns_apiserver_v1.Stray.AddStrays:output_type -> google.protobuf.Empty
	1,  // 18: y7_redns_apiserver_v1.Stray.ListStrays:output_type -> y7_redns_apiserver_v1.DetailedStrayEntity
	21, // 19: y7_redns_apiserver_v1.Stray.DeleteStrayById:output_type -> google.protobuf.Empty
	9,  // 20: y7_redns_apiserver_v1.Stray.DeleteStrayByValue:output_type -> y7_redns_apiserver_v1.StrayDeleteResponses
	14, // 21: y7_redns_apiserver_v1.Stray.ModifyStray:output_type -> y7_redns_apiserver_v1.ResultMsg
	16, // 22: y7_redns_apiserver_v1.Redns.AddGeneration:output_type -> y7_redns_apiserver_v1.AddGenerationResponse
	20, // 23: y7_redns_apiserver_v1.Redns.DeleteGenerationById:output_type -> y7_redns_apiserver_v1.PerServerRednsGenerationDeleteByIdResult
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_redns_rpc_proto_init() }
func file_redns_rpc_proto_init() {
	if File_redns_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_redns_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetailedStrayEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redns_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RRidentifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redns_rpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StrayEntity2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redns_rpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StrayEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redns_rpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StrayDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redns_rpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StrayDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redns_rpc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PerServerStrayDeleteByIdResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redns_rpc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StrayByValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redns_rpc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StrayDeleteResponses); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redns_rpc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StrayModifyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redns_rpc_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StrayModifyRequests); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redns_rpc_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StrayModifyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redns_rpc_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StrayModifyResponses); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redns_rpc_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redns_rpc_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGenerationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redns_rpc_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGenerationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redns_rpc_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rfc1035); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redns_rpc_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGenerationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redns_rpc_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RednsGenerationDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redns_rpc_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PerServerRednsGenerationDeleteByIdResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_redns_rpc_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*StrayEntity2_Identifier)(nil),
		(*StrayEntity2_Rfc1035)(nil),
	}
	file_redns_rpc_proto_msgTypes[9].OneofWrappers = []interface{}{}
	file_redns_rpc_proto_msgTypes[13].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_redns_rpc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_redns_rpc_proto_goTypes,
		DependencyIndexes: file_redns_rpc_proto_depIdxs,
		EnumInfos:         file_redns_rpc_proto_enumTypes,
		MessageInfos:      file_redns_rpc_proto_msgTypes,
	}.Build()
	File_redns_rpc_proto = out.File
	file_redns_rpc_proto_rawDesc = nil
	file_redns_rpc_proto_goTypes = nil
	file_redns_rpc_proto_depIdxs = nil
}
